package com.example.covid19shahajjo.activities;

import androidx.appcompat.app.AppCompatActivity;
import androidx.recyclerview.widget.LinearLayoutManager;
import androidx.recyclerview.widget.RecyclerView;
import android.os.Bundle;
import com.example.covid19shahajjo.R;
import com.example.covid19shahajjo.models.YouTubeVideos;
import com.google.firebase.database.DatabaseReference;
import com.google.firebase.database.FirebaseDatabase;


public class Covid19StoryActivity extends AppCompatActivity {

    private DatabaseReference databaseReference;
    private RecyclerView storyRecyclerView;
    private Covid19StoryActivity covid19StoryActivity;


    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_covid19_story);
        covid19StoryActivity=this;



        storyRecyclerView = (RecyclerView) findViewById(R.id.recyclerview_video);
        storyRecyclerView.setHasFixedSize(true);
        storyRecyclerView.setLayoutManager(new LinearLayoutManager(this));

        databaseReference = FirebaseDatabase.getInstance().getReference("video");

        YouTubeVideos youTubeVideos=new YouTubeVideos(covid19StoryActivity,null,null);

        /*********************************ADD VIDEO INFO TO FIREBASE*********************************************/

        //Add youtubeVideo data to firebase

       /* Data Schema :

        video:
            autoGenerated Id:
                            title: about the video or selialization
                            url:  zx6uMCoW2gQ  //https://www.youtube.com/watch?v=zx6uMCoW2gQ


        youTubeVideos.addYoutubeVideoData(databaseReference,"about the video or selialization","zx6uMCoW2gQ");

        */

        /*********************************DELETE AND UPDATE VIDEO TO FIREBASE*********************************************/

       /*

        //delete a video information with title
        youTubeVideos.deleteYoutubeVideoData(databaseReference,"Test");

        //update title with presentTitle
//        youTubeVideos.updateYoutubeVideoTitleData();

        //update url with presentTitle
//        youTubeVideos.updateYoutubeVideoUrlData();

        //update title+ url with presentTitle
        youTubeVideos.updateYoutubeVideoData(databaseReference,"Empty","About Corona virus","PSnSo9kYlH4");*/


       /*********************************GET VIDEO INFO FROM FIREBASE*********************************************/

        //get Youtube data from firebase and show on recycle view (VideoAdapter)
        youTubeVideos.getYoutubeVideoData(databaseReference,storyRecyclerView);



    }

    @Override
    protected void onPause() {
        super.onPause();
    }
}
